spring:
  application:
    name: blog-portal
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: blog-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /bmsblog/bloginfo/**
      - /blogs/**
      - /bmsclassify/viewClassifyList/**


# 自定义redis key
redis:
  database: blog
  key:
    authCode: 'ums:authCode'
    member: 'ums:member'
    views: 'bms:views'   # blog:bms:views:blogid = 100
    isviews: 'bms:isviews' # blog:bms:isviews:blogid:umsid/ip = 0/1

  expire:
    authCode: 90 # 验证码超期时间
    isviews: 10800 # 浏览时间 3 小时时效
    common: 86400 # 24小时



# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

